### ISSUE TITLE
The notes are not saved to _notes

### ISSUE THREAD

**Issue by EncryptedKishor** [domOrielton/minimal-web-notepad#1]
The new notes are not saved? How to solve this?

**Comment by domOrielton** [comment]
I think this is a permissions issue... Can you confirm _notes exists and has the right permission for the folder? 755 or 744 should be just fine - example below from my test version which I tested 755 and 744 on

![permissions](https://user-images.githubusercontent.com/16351596/62374422-d996a980-b533-11e9-9a3a-f8720a1a16b9.jpg)


I've  also added a new setup.php file that will check the _notes directory  can be written to.  If it can't you can either change the permissions or  delete the _notes directory and then setup.php will create it for you  and it should hopefully be writable then.

**Comment by domOrielton** [comment]
I've also added a setup.php file that will check the _notes directory can be written to.  If it can't you can either change the permissions or delete the _notes directory and then setup.php will create it for you and it should hopefully be writable then.

**Comment by khattam12** [comment]
Both methods not working :/

**Comment by EncryptedKishor** [comment]
Worked! Thank you!!  💯

**Comment by domOrielton** [comment]
Excellent, glad it was just a permissions issue. This has definitely caught me out before!
