### ISSUE TITLE
能不能添加个文件上传功能，然后在list页面展示文件上传列表？ Can you add a file upload function, and then display the file upload list on the list page?

### ISSUE THREAD

**Issue by twamix** [domOrielton/minimal-web-notepad#5]
RT

**Comment by domOrielton** [comment]
Unfortunately I have no plan to add a file upload option. 

There are many excellent open source file upload applications that you could use if you need this functionality.

**Comment by domOrielton** [comment]
I've added a translation of the title in English using Google Translate. Hopefully it is correct
